### ISSUE TITLE
.net core or .net 5 support

### ISSUE THREAD

**Issue by mpriem** [CrayonGroup/crayon-api-sdk#21]
Hi,

Are there any plans to support .net core or .net 5?
We are running linux and Azure functions, so it would be great to use the SDK on these platforms.

Thanks,

Mark

**Comment by afsghase** [comment]
You can call endpoints directly. No plan to release a .net core sdk for now. The sdk is just a wrapper for endpoints, so no big deal if you call endpoints directly.
